[book]
title = "Getting Started with Universal Scene Description (USD)"
authors = ["Remedy Entertainment Plc"]
language = "en"
# multilingual = false
src = "src"

[output.html]


# git-repository-url = "https://github.com/Remedy-Entertainment/USDBook"
# edit-url-template = "https://github.com/Remedy-Entertainment/USDBook/edit/develop/{path}"
additional-css = [
    "theme/custom.css",
    'theme/mdbook-admonish.css',
    'theme/catppuccin.css',
    'theme/catppuccin-highlight.css', "./mdbook-admonish.css",
]
no-section-label = true

[output.html.fold]
enable = true
level = 4
